-- Adds the Job Route Card number (JC No) to "production route cards".
-- Format: JC-NNN, the same "highest existing suffix + 1" pattern as PRD-NNN
-- and DC-NNN -- generated by the frontend on Production Planning submit
-- (generateNextJcNo in routeCards.js). A collision fails on the unique
-- constraint (23505) rather than silently duplicating.
--
-- Existing cards are backfilled JC-001, JC-002, ... in the order they were
-- planned, so every card has a number before NOT NULL is applied. Runs in
-- one transaction: if any step fails, nothing is changed.

begin;

alter table "production route cards"
  add column jc_no text;

update "production route cards" c
set jc_no = 'JC-' || lpad(n.rn::text, 3, '0')
from (
  select prd_no, row_number() over (order by planned_date, created_at, prd_no) as rn
  from "production route cards"
) n
where c.prd_no = n.prd_no
  and c.jc_no is null;

alter table "production route cards"
  alter column jc_no set not null;

alter table "production route cards"
  add constraint production_route_cards_jc_no_key unique (jc_no);

commit;

-- After running:
--   select count(*) as cards, count(jc_no) as numbered, count(distinct jc_no) as distinct_nos
--   from "production route cards";          -- all three should be equal
--   notify pgrst, 'reload schema';
